### ISSUE TITLE
Build and publish wheels for UCXX

### ISSUE THREAD

**Issue by pentschev** [rapidsai/ucxx#145]
We're getting close to making the move from UCX-Py to UCXX, PRs such as https://github.com/rapidsai/raft/pull/1983 and https://github.com/rapidsai/cuml/pull/5697 are integrating UCXX to run tests in CI. The plan is, time permitting, to have RAPIDS projects running UCXX tests in CI for 24.02 and possibly switching to UCXX as the default in 24.04 (still pending approval). However, we cannot make that move without also publishing wheels.

@vyasr would you be able to work on wheels for UCXX sometime before 24.02? I'll be OOO until early January, so if you don't have the bandwidth to work on it I may need your help then, unless @charlesbluca or @wence- have some bandwidth, more importantly, want to give it a go at this. 🙂

**Comment by vyasr** [comment]
I don't think I'll be able to work on this any time in the near future, but I am happy to advise if someone else wants to get it started! The process has gotten a lot simpler so hopefully modeling after other repos should get us most of the way there (obviously some extra complexity around bundling ucx libraries but hopefully the code in ucx-py helps explain how we do that well enough).
