### ISSUE TITLE
Discovering Significant Bandwidth Differences in Data Transfer Using tag_send with UCX and  UCXX 

### ISSUE THREAD

**Issue by fanfanaaaa** [rapidsai/ucxx#249]
I want to test the bandwidth of the data transfer by using the tag_send/tag_recv, but I found that the UCXX and UCX libraries have a large difference in the test bandwidth.
1. ucxx lib
$  ./benchmarks/ucxx perftest -m blocking -s 10000000 -n 1000 &  ./benchmarks/ucxx perftest  192.168.0.215 -m blocking -s 10000000 -n 1000
2. ucx lib
$  ucx _perftest -t tag_sync_bw -s 10000000 -n 1000 & ucx _perftest 192.168.0.215 -t tag_sync_bw -s 10000000 -n 1000
 ucxx_perftest results are about 3GB/s, while the ucx_perftest can reach about 20GB/s, why is the difference so big between the two tests, is it because the C++ version is not as good as the C version in terms of implementation performance？Can a more efficient C++ version be provided?

**Comment by pentschev** [comment]
Thanks for the report @fanfanaaaa . I think this has to do with the fact that UCXX benchmark currently enables endpoint error handling by default and that imposes different performance pressure depending on the transports being used. If you specify `-e` to `ucx_perftest`, do you see a similar performance to `ucxx_perftest`? Also, would you mind trying out https://github.com/rapidsai/ucxx/pull/250? In it I've added the `-e` option as well with it now turned off by default to match what `ucx_perftest` does.

**Comment by pentschev** [comment]
#250 is merged and the new default is not to enable endpoint error handling (like `ucx_perftest` default), which should result in similar performance. Please feel free to reopen if you find any major performance differences still, or open a new issue if you find other problems.
