### ISSUE TITLE
Add `arm` support

### ISSUE THREAD

**Issue by ajschmidt8** [rapidsai/ucxx#27]
In #18, we disabled `arm` builds and tests due to some issues.

We should eventually re-add `arm` support when time permits.

To re-enable `arm` builds and tests, the changes from the commit below need to be reverted:

- https://github.com/rapidsai/ucxx/pull/18/commits/a9bf496cbe0799f375ca6e842e4df7a9d6644213

**Comment by pentschev** [comment]
This has been resolved via https://github.com/rapidsai/ucxx/pull/84 and https://github.com/rapidsai/ucxx/pull/83.
