### ISSUE TITLE
UCXX: CUDA 12 Conda Packages

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/ucxx#59]
Pushing for CUDA 12 Conda package builds of libraries for RAPIDS 23.08. This issue is for tracking that work.

Requirements (please recheck):

```[tasklist]
### Developer tasks
- [x] I've confirmed the list below is correct (or updated if not)
```

```[tasklist]
### Required dependencies from Conda
- [x] https://github.com/conda-forge/pynvml-feedstock/pull/11
- [x] https://github.com/conda-forge/ucx-split-feedstock/issues/116
- [ ] https://github.com/rapidsai/rmm/issues/1207
```

```[tasklist]
### Test dependencies from conda-forge
- [x] https://github.com/conda-forge/cupy-feedstock/issues/139
- [x] https://github.com/conda-forge/numba-feedstock/issues/112
- [x] `nvtx`
```

```[tasklist]
### RAPIDS test dependencies
- [ ] https://github.com/rapidsai/cudf/issues/12771
```

**Comment by jakirkham** [comment]
@pentschev could you please add or update any dependencies in the lists above?

**Comment by pentschev** [comment]
Thanks @jakirkham , this looks mostly right. The only adjustment I've made is to move RMM from test dependency to [required dependency from conda](https://github.com/rapidsai/ucxx/blob/branch-0.33/conda/recipes/ucxx/meta.yaml#L165).
